"use strict";
const http = require("node:http");
const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");
const { DatabaseSync } = require("node:sqlite");
const PORT = Number(process.env.PORT || 3000), ROOT = __dirname, PUBLIC_ROOT = path.join(ROOT, "public"), production = process.env.NODE_ENV === "production";
if (production && !process.env.SESSION_SECRET) throw new Error("SESSION_SECRET must be set in production.");
const SECRET = process.env.SESSION_SECRET || crypto.randomBytes(32).toString("hex");
if (!production && !process.env.SESSION_SECRET) console.warn("SESSION_SECRET is not set; development sessions expire when the server restarts.");

fs.mkdirSync(path.join(ROOT, "data"), { recursive: true });
const db = new DatabaseSync(path.join(ROOT, "data", "finance-buddy.sqlite"));
db.exec(`PRAGMA journal_mode = WAL; PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, full_name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('parent','child')), parent_id INTEGER REFERENCES users(id), everyday_cents INTEGER NOT NULL DEFAULT 0, emergency_cents INTEGER NOT NULL DEFAULT 0, savings_cents INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS transactions (id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), type TEXT NOT NULL, amount_cents INTEGER NOT NULL, note TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS approvals (id INTEGER PRIMARY KEY, child_id INTEGER NOT NULL REFERENCES users(id), parent_id INTEGER REFERENCES users(id), amount_cents INTEGER NOT NULL, reason TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','rejected')), reviewed_by INTEGER REFERENCES users(id), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS app_events (id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), action TEXT NOT NULL, details TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
`);
for (const [table, column] of [["users", "parent_id"], ["approvals", "parent_id"]]) {
  if (!db.prepare(`PRAGMA table_info(${table})`).all().some(item => item.name === column)) db.exec(`ALTER TABLE ${table} ADD COLUMN ${column} INTEGER REFERENCES users(id)`);
}
db.exec("CREATE INDEX IF NOT EXISTS approvals_parent_status_idx ON approvals(parent_id, status, id); CREATE INDEX IF NOT EXISTS transactions_user_created_idx ON transactions(user_id, created_at DESC);");

const attempts = new Map();
function headers(res) { res.setHeader("X-Content-Type-Options", "nosniff"); res.setHeader("X-Frame-Options", "DENY"); res.setHeader("Referrer-Policy", "strict-origin-when-cross-origin"); res.setHeader("Permissions-Policy", "camera=(), microphone=(), geolocation=()"); }
function send(res, status, body, type = "application/json; charset=utf-8") { headers(res); res.writeHead(status, { "Content-Type": type, "Cache-Control": "no-store" }); res.end(type.startsWith("application/json") ? JSON.stringify(body) : body); }
function bad(res, message, status = 400) { send(res, status, { error: message }); }
function requestError(message, status) { const error = new Error(message); error.status = status; error.expose = true; return error; }
function parseJson(req) { return new Promise((resolve, reject) => { let body = "", done = false; const fail = error => { if (!done) { done = true; reject(error); } }; req.on("data", chunk => { body += chunk; if (Buffer.byteLength(body) > 100000) { fail(requestError("Request body is too large.", 413)); req.destroy(); } }); req.on("end", () => { if (done) return; try { done = true; resolve(body ? JSON.parse(body) : {}); } catch { fail(requestError("Invalid JSON body.", 400)); } }); req.on("error", () => fail(requestError("Could not read the request body.", 400))); }); }
function email(value) { return String(value || "").trim().toLowerCase(); }
function clean(value, max) { return String(value || "").trim().replace(/\s+/g, " ").slice(0, max); }
function cents(value) { const text = typeof value === "string" || typeof value === "number" ? String(value).trim() : ""; if (!/^\d+(\.\d{1,2})?$/.test(text)) return 0; const amount = Math.round(Number(text) * 100); return Number.isSafeInteger(amount) && amount > 0 && amount <= 100000000 ? amount : 0; }
function hash(password, salt = crypto.randomBytes(16).toString("hex")) { return new Promise((resolve, reject) => crypto.scrypt(password, salt, 64, (error, key) => error ? reject(error) : resolve(`${salt}:${key.toString("hex")}`))); }
async function matches(password, stored) { const [salt, expected] = String(stored).split(":"); if (!salt || !expected) return false; const actual = (await hash(password, salt)).split(":")[1], a = Buffer.from(actual, "hex"), b = Buffer.from(expected, "hex"); return a.length === b.length && crypto.timingSafeEqual(a, b); }
function tokenFor(user) { const payload = Buffer.from(JSON.stringify({ id: user.id, role: user.role, exp: Date.now() + 604800000 })).toString("base64url"); return `${payload}.${crypto.createHmac("sha256", SECRET).update(payload).digest("base64url")}`; }
function currentUser(req) { const match = (req.headers.authorization || "").match(/^Bearer ([A-Za-z0-9_-]+\.[A-Za-z0-9_-]+)$/); if (!match) return null; const [payload, signature] = match[1].split("."), expected = crypto.createHmac("sha256", SECRET).update(payload).digest("base64url"); if (signature.length !== expected.length || !crypto.timingSafeEqual(Buffer.from(signature), Buffer.from(expected))) return null; try { const session = JSON.parse(Buffer.from(payload, "base64url").toString("utf8")); if (!Number.isInteger(session.id) || session.exp < Date.now()) return null; return db.prepare("SELECT id, full_name, email, role, parent_id, everyday_cents, emergency_cents, savings_cents FROM users WHERE id = ?").get(session.id) || null; } catch { return null; } }
function requireUser(req, res) { const user = currentUser(req); if (!user) { bad(res, "Please sign in to continue.", 401); return null; } return user; }
function publicUser(user) { return { id: user.id, fullName: user.full_name, email: user.email, role: user.role, parentLinked: Boolean(user.parent_id) }; }
function limited(req) { const key = `${req.socket.remoteAddress}:${new URL(req.url, "http://localhost").pathname}`, now = Date.now(), recent = (attempts.get(key) || []).filter(time => now - time < 600000); recent.push(now); attempts.set(key, recent); return recent.length > 10; }

async function api(req, res, pathname) {
  if ((pathname === "/api/auth/login" || pathname === "/api/auth/register") && limited(req)) return bad(res, "Too many attempts. Please try again in a few minutes.", 429);
  if (req.method === "POST" && pathname === "/api/auth/register") {
    const body = await parseJson(req), fullName = clean(body.fullName, 100), address = email(body.email), password = typeof body.password === "string" ? body.password : "", role = body.role;
    if (fullName.length < 2) return bad(res, "Enter a name with at least 2 characters."); if (!/^\S+@\S+\.\S+$/.test(address)) return bad(res, "Enter a valid email address."); if (password.length < 10 || password.length > 200) return bad(res, "Password must be between 10 and 200 characters."); if (!["parent", "child"].includes(role)) return bad(res, "Select Parent or Child.");
    let parent = null; if (role === "child") { const parentAddress = email(body.parentEmail); if (!parentAddress) return bad(res, "Enter the email address of your registered parent account."); parent = db.prepare("SELECT id, role FROM users WHERE email = ?").get(parentAddress); if (!parent || parent.role !== "parent") return bad(res, "No parent account was found for that email address."); }
    try { const result = db.prepare("INSERT INTO users (full_name, email, password_hash, role, parent_id) VALUES (?, ?, ?, ?, ?)").run(fullName, address, await hash(password), role, parent?.id || null), user = db.prepare("SELECT * FROM users WHERE id = ?").get(result.lastInsertRowid); return send(res, 201, { token: tokenFor(user), user: publicUser(user), redirectTo: role === "child" ? "/kids" : "/dashboard" }); } catch (error) { return bad(res, String(error.message).includes("UNIQUE") ? "An account already exists for this email." : "Could not create account."); }
  }
  if (req.method === "POST" && pathname === "/api/auth/login") { const body = await parseJson(req), user = db.prepare("SELECT * FROM users WHERE email = ?").get(email(body.email)); if (!user || !(await matches(typeof body.password === "string" ? body.password : "", user.password_hash))) return bad(res, "Email or password is incorrect.", 401); return send(res, 200, { token: tokenFor(user), user: publicUser(user), redirectTo: user.role === "child" ? "/kids" : "/dashboard" }); }
  if (req.method === "GET" && pathname === "/api/me") { const user = requireUser(req, res); if (user) send(res, 200, { user: publicUser(user) }); return; }
  if (req.method === "POST" && pathname === "/api/events") { const user = requireUser(req, res); if (!user) return; const body = await parseJson(req), action = clean(body.action, 80); if (!action) return bad(res, "An action name is required."); db.prepare("INSERT INTO app_events (user_id, action, details) VALUES (?, ?, ?)").run(user.id, action, clean(body.details, 500)); return send(res, 201, { message: "Action saved." }); }
  if (req.method === "GET" && pathname === "/api/dashboard") { const user = requireUser(req, res); if (!user) return; const pending = user.role === "parent" ? db.prepare("SELECT id, amount_cents, reason FROM approvals WHERE parent_id = ? AND status = 'pending' ORDER BY id DESC LIMIT 1").get(user.id) : null, total = user.everyday_cents + user.emergency_cents + user.savings_cents; return send(res, 200, { user: publicUser(user), balances: { everyday: user.everyday_cents, emergency: user.emergency_cents, savings: user.savings_cents, total }, pendingApproval: pending && { id: pending.id, amount: pending.amount_cents, reason: pending.reason }, goal: { current: user.savings_cents, target: Math.max(user.savings_cents, 80000) } }); }
  if (req.method === "GET" && pathname === "/api/children") { const user = requireUser(req, res); if (!user) return; if (user.role !== "parent") return bad(res, "Only a parent can view linked child accounts.", 403); const children = db.prepare("SELECT id, full_name, email, everyday_cents, emergency_cents, savings_cents, created_at FROM users WHERE parent_id = ? ORDER BY full_name").all(user.id).map(child => ({ id: child.id, fullName: child.full_name, email: child.email, balances: { everyday: child.everyday_cents, emergency: child.emergency_cents, savings: child.savings_cents, total: child.everyday_cents + child.emergency_cents + child.savings_cents }, createdAt: child.created_at })); return send(res, 200, { children }); }
  if (req.method === "GET" && pathname === "/api/transactions") { const user = requireUser(req, res); if (!user) return; const rows = user.role === "parent" ? db.prepare("SELECT t.id, t.type, t.amount_cents, t.note, t.created_at, u.full_name FROM transactions t JOIN users u ON u.id = t.user_id WHERE t.user_id = ? OR u.parent_id = ? ORDER BY t.id DESC LIMIT 100").all(user.id, user.id) : db.prepare("SELECT t.id, t.type, t.amount_cents, t.note, t.created_at, u.full_name FROM transactions t JOIN users u ON u.id = t.user_id WHERE t.user_id = ? ORDER BY t.id DESC LIMIT 100").all(user.id); return send(res, 200, { transactions: rows.map(row => ({ id: row.id, type: row.type, amount: row.amount_cents, note: row.note, createdAt: row.created_at, accountName: row.full_name })) }); }
  if (req.method === "POST" && pathname === "/api/funds") { const user = requireUser(req, res); if (!user) return; if (user.role !== "parent") return bad(res, "Only a parent can fund a wallet.", 403); const body = await parseJson(req), amount = cents(body.amount); if (!amount) return bad(res, "Enter a positive amount with no more than two decimal places."); const everyday = Math.round(amount * .5), emergency = Math.round(amount * .2), savings = amount - everyday - emergency; db.prepare("UPDATE users SET everyday_cents = everyday_cents + ?, emergency_cents = emergency_cents + ?, savings_cents = savings_cents + ? WHERE id = ?").run(everyday, emergency, savings, user.id); db.prepare("INSERT INTO transactions (user_id, type, amount_cents, note) VALUES (?, 'fund', ?, ?)").run(user.id, amount, clean(body.note || "Wallet funded", 200)); return send(res, 201, { message: "Wallet funded and allocated across all three buckets." }); }
  if (req.method === "POST" && pathname === "/api/approvals") { const user = requireUser(req, res); if (!user) return; if (user.role !== "child") return bad(res, "Only a child account can request an approval.", 403); const body = await parseJson(req), amount = cents(body.amount), reason = clean(body.reason, 300); if (!amount || reason.length < 4) return bad(res, "Include a positive amount and a short reason."); if (!user.parent_id) return bad(res, "Link this child account to a parent before submitting a request.", 409); if (db.prepare("SELECT id FROM approvals WHERE child_id = ? AND amount_cents = ? AND reason = ? AND status = 'pending'").get(user.id, amount, reason)) return bad(res, "An identical request is already awaiting review.", 409); db.prepare("INSERT INTO approvals (child_id, parent_id, amount_cents, reason) VALUES (?, ?, ?, ?)").run(user.id, user.parent_id, amount, reason); return send(res, 201, { message: "Your request is ready for your parent to review." }); }
  if (req.method === "POST" && /^\/api\/approvals\/\d+\/review$/.test(pathname)) { const user = requireUser(req, res); if (!user) return; if (user.role !== "parent") return bad(res, "Only a parent can review requests.", 403); const id = Number(pathname.split("/")[3]), { decision } = await parseJson(req); if (!["approved", "rejected"].includes(decision)) return bad(res, "Choose approved or rejected."); db.exec("BEGIN IMMEDIATE"); try { const approval = db.prepare("SELECT * FROM approvals WHERE id = ? AND parent_id = ? AND status = 'pending'").get(id, user.id); if (!approval) throw requestError("This request is no longer pending.", 404); if (decision === "approved") { const parent = db.prepare("SELECT savings_cents FROM users WHERE id = ?").get(user.id); if (parent.savings_cents < approval.amount_cents) throw requestError("Your savings balance is too low to approve this request.", 409); db.prepare("UPDATE users SET savings_cents = savings_cents - ? WHERE id = ?").run(approval.amount_cents, user.id); db.prepare("UPDATE users SET everyday_cents = everyday_cents + ? WHERE id = ?").run(approval.amount_cents, approval.child_id); db.prepare("INSERT INTO transactions (user_id, type, amount_cents, note) VALUES (?, 'release', ?, ?)").run(approval.child_id, approval.amount_cents, `Parent-approved release: ${approval.reason}`); } db.prepare("UPDATE approvals SET status = ?, reviewed_by = ? WHERE id = ?").run(decision, user.id, id); db.exec("COMMIT"); return send(res, 200, { message: decision === "approved" ? "Request approved and funds released to the child's spending wallet." : "Request rejected." }); } catch (error) { try { db.exec("ROLLBACK"); } catch {} throw error; } }
  return bad(res, "API endpoint not found.", 404);
}

const pages = { "/": "lending.html", "/lending": "lending.html", "/login": "login.html", "/register": "register.html", "/dashboard": "dashboard.html", "/kids": "Wallet.html", "/child": "child.html", "/my-child": "my-child.html", "/allowance": "allownance.html", "/goals": "savinggoals1.html", "/activity": "Transaction.html", "/transactions": "Transaction.html", "/learning": "learning.html" };
const mimes = { ".css": "text/css; charset=utf-8", ".js": "application/javascript; charset=utf-8", ".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".png": "image/png", ".svg": "image/svg+xml", ".html": "text/html; charset=utf-8" };
function page(file) { return fs.readFileSync(path.join(PUBLIC_ROOT, file), "utf8").replace("</body>", '<script src="/client.js" defer></script></body>'); }
function staticFile(res, pathname) { const file = path.resolve(PUBLIC_ROOT, `.${decodeURIComponent(pathname)}`); if (!file.startsWith(`${PUBLIC_ROOT}${path.sep}`) || !fs.existsSync(file) || !fs.statSync(file).isFile()) return false; if (path.extname(file) === ".html") send(res, 200, page(path.basename(file)), mimes[".html"]); else send(res, 200, fs.readFileSync(file), mimes[path.extname(file).toLowerCase()] || "application/octet-stream"); return true; }
http.createServer(async (req, res) => { const pathname = new URL(req.url, `http://${req.headers.host || "localhost"}`).pathname; try { if (pathname.startsWith("/api/")) return await api(req, res, pathname); if (pathname === "/client.js") return send(res, 200, fs.readFileSync(path.join(ROOT, "client.js"), "utf8"), mimes[".js"]); if (pathname === "/emergency") return send(res, 200, page(currentUser(req)?.role === "child" ? "emergencyC.html" : "emergencyP.html"), mimes[".html"]); if (pages[pathname]) return send(res, 200, page(pages[pathname]), mimes[".html"]); if (staticFile(res, pathname)) return; return send(res, 404, "Not found", "text/plain; charset=utf-8"); } catch (error) { if (!error.expose) console.error(error); return bad(res, error.expose ? error.message : "Unexpected server error.", error.status || 500); } }).listen(PORT, () => console.log(`FinanceBuddy is running at http://localhost:${PORT}`));
